#!/bin/bash 
if [[ $# -ne 2 ]] ; then
    echo 'usage $0 username fsname-mdtnumber; i.e. $0 cl3-audit exafs-MDT0000'
    exit 0
fi

BINDIR=/opt/ddn/flaudit
USER=$1
MDT=$2
$BINDIR/flaudit -u "$USER" "$MDT" | $BINDIR/fluent-bit -c $BINDIR/fluent-bit.conf
